### ISSUE TITLE
Back button inside a form

### ISSUE THREAD

**Issue by grjkz** [grjkz/grjkzP2.github.io#1]
I'm trying to make the back button only redirect. The problem is, I'm trying to get it to work inside a POST form. Can it be done?

```
<form action="/boards/<%=path%>" method="POST">
        <div class="row">
            <div class="row">
                <label for="topic-input">Topic:</label>
            </div>
            <div class="row">
                <input type="text" placeholder='Topic' name='topic' id='topic-input'>
            </div>
        </div>
        <div class="row">
            <div class="row">
                <label for="detail-input">Comment:</label>
            </div>
            <div class="row">
                <textarea name="detail" id="detail-input" cols="30" rows="10"></textarea>
            </div>
        </div>

        <div class="row">
            <div class="small-6 medium-9 columns">
                <form action="/boards/<%=path%>" method='GET'>
                    <button type='button' action='/boards/<%=path%>'>Back</button>
                </form>
            </div>
            <div class="small-6 medium-3 columns end">
                <button>Create Thread</button>
            </div>
        </div>
    </form>
```

**Comment by justingohde-ga** [comment]
If you don't want to POST data, could you make the method =GET?

On Thu, Aug 13, 2015 at 10:21 AM, grjkz <notifications@github.com> wrote:

> Assigned #1 <https://github.com/grjkz/grjkzP2.github.io/issues/1> to
> @justingohde-ga <https://github.com/justingohde-ga>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grjkz/grjkzP2.github.io/issues/1#event-381500209>.
>



-- 
-Justin Gohde
Instructor, Web Development Immersive
General Assembly

**Comment by justingohde-ga** [comment]
The window object keeps track of the browser history:

https://developer.mozilla.org/en-US/docs/Web/API/Window/history

On Thu, Aug 13, 2015 at 10:29 AM, Justin Gohde <
justin.gohde@generalassemb.ly> wrote:

> If you don't want to POST data, could you make the method =GET?
>
> On Thu, Aug 13, 2015 at 10:21 AM, grjkz <notifications@github.com> wrote:
>
>> Assigned #1 <https://github.com/grjkz/grjkzP2.github.io/issues/1> to
>> @justingohde-ga <https://github.com/justingohde-ga>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/grjkz/grjkzP2.github.io/issues/1#event-381500209>.
>>
>
>
>
> --
> -Justin Gohde
> Instructor, Web Development Immersive
> General Assembly
>



-- 
-Justin Gohde
Instructor, Web Development Immersive
General Assembly

**Comment by grjkz** [comment]
The form for the "Back" button has method="GET", but it would still post
