### ISSUE TITLE
Problem trying to get main.js to work

### ISSUE THREAD

**Issue by grjkz** [grjkz/grjkzP2.github.io#2]
The purpose of what I'm trying to do is to get my main.js file working with sqlite3 so that I can use onclick() to update the db votes.

When main.js is in the static folder:

```
<script type='text/javascript' src='/main.js'></script>
```

It links with the page BUT it can't require('sqlite3');

When I move main.js up to the root alongside the app.js file:

```
<script type='text/javascript' src='../main.js'></script>
plus other variations of stuff to path into it
```

The script doesn't link anymore

**Comment by justingohde-ga** [comment]
the ```require('sqlite3)``` javascript command is a node.js method. It doesn't exist in "standard" javascript. Rather than using an onclick() method, have you thought about making the vote button issue a PUT request to modify the database?

**Comment by justingohde-ga** [comment]
Your server should modify the database, not the client

**Comment by justingohde-ga** [comment]
the <script> tag that you are trying to use is for scripts executed by the browser (client)

**Comment by grjkz** [comment]
uh... i don't really understand the difference between 'node.js method' and 'standard javascript'.
 But I'm guessing it wont work. Thought it would since they're both .js files. I was hoping that I could use Javascript for something so I figure I'd start with this:
```
var upvote = function(id) {
	db.run('UPDATE threads SET votes+votes+1 WHERE id=?',id, function(err) {
		if (err) throw err;
		else console.log('upvote went thru');
	});
}
```

**Comment by justingohde-ga** [comment]
So, node.js is a javascript library run on a server. <script> tags are meant for html pages, which means that they are "run" by a browser (ie the client). 

Why don't you relocate that same functionality to a PUT request route handled by your server?
